import z from 'zod'

export const SysLogBaseSchema = z.object({
    id: z.string().nullish(),
    userId: z.string().nullish(),
    username: z.string().nullish().meta({ query: 'like' }),
    ip: z.string().nullish().meta({ query: 'like' }),
    userAgent: z.string().nullish(),
    browser: z.string().nullish(),
    os: z.string().nullish(),
    requestMethod: z.string().nullish(),
    requestPath: z.string().nullish().meta({ query: 'like' }),
    trpcType: z.string().nullish(),
    trpcPath: z.string().nullish().meta({ query: 'like' }),
    durationMs: z.number().nullish(),
    requestParams: z.unknown().nullish(),
    requestResult: z.unknown().nullish(),
    errorCode: z.string().nullish().meta({ query: 'like' }),
    traceId: z.string().nullish().meta({ query: 'like' }),
    level: z.number().nullish(),
    module: z.string().nullish().meta({ query: 'like' }),
    message: z.string().nullish().meta({ query: 'like' }),
    trace: z.string().nullish(),
    status: z.number().nullish(),
    remark: z.string().nullish().meta({ query: 'like' }),
    createdBy: z.string().nullish(),
    createdAt: z.string().nullish(),
    updatedBy: z.string().nullish(),
    updatedAt: z.string().nullish(),
    isDeleted: z.number().nullish(),
})
export type SysLogDto = z.infer<typeof SysLogBaseSchema>
