import { mysqlTable, primaryKey, unique, index, varchar, tinyint, int, decimal, timestamp } from "drizzle-orm/mysql-core"

export const sysMemberLevelOrder = mysqlTable("sys_member_level_order", {
	id: varchar({ length: 36 }).notNull(),
	outTradeNo: varchar("out_trade_no", { length: 64 }).notNull(),
	requestId: varchar("request_id", { length: 64 }),
	userId: varchar("user_id", { length: 36 }).notNull(),
	levelId: varchar("level_id", { length: 36 }).notNull(),
	levelName: varchar("level_name", { length: 50 }).notNull(),
	durationDays: int("duration_days").default(0).notNull(),
	priceAmount: decimal("price_amount", { precision: 12, scale: 2 }).default('0.00').notNull(),
	payAmount: decimal("pay_amount", { precision: 12, scale: 2 }).default('0.00').notNull(),
	payMode: varchar("pay_mode", { length: 20 }).default('balance').notNull(),
	status: varchar({ length: 10 }).default('WP').notNull(),
	freezeId: varchar("freeze_id", { length: 36 }),
	payOrderId: varchar("pay_order_id", { length: 36 }),
	payChannelCode: varchar("pay_channel_code", { length: 30 }),
	startAt: timestamp("start_at", { mode: 'string' }),
	endAt: timestamp("end_at", { mode: 'string' }),
	paidAt: timestamp("paid_at", { mode: 'string' }),
	effectiveAt: timestamp("effective_at", { mode: 'string' }),
	expireAt: timestamp("expire_at", { mode: 'string' }),
	failReason: varchar("fail_reason", { length: 500 }),
	remark: varchar({ length: 255 }),
	createdBy: varchar("created_by", { length: 36 }),
	createdAt: timestamp("created_at", { mode: 'string' }).defaultNow().notNull(),
	updatedBy: varchar("updated_by", { length: 36 }),
	updatedAt: timestamp("updated_at", { mode: 'string' }).defaultNow().onUpdateNow().notNull(),
	isDeleted: tinyint("is_deleted").default(0),
},
(table) => [
	index("idx_member_level_order_user").on(table.userId, table.createdAt),
	index("idx_member_level_order_status").on(table.status, table.expireAt),
	index("idx_member_level_order_pay").on(table.payOrderId),
	primaryKey({ columns: [table.id], name: "sys_member_level_order_id" }),
	unique("uk_member_level_order_out").on(table.outTradeNo),
	unique("uk_member_level_order_request").on(table.requestId),
]);
