import { mysqlTable, primaryKey, unique, index, varchar, tinyint, int, decimal, timestamp } from "drizzle-orm/mysql-core"

export const sysOrder = mysqlTable("sys_order", {
	id: varchar({ length: 36 }).notNull(),
	orderNo: varchar("order_no", { length: 64 }).notNull(),
	requestId: varchar("request_id", { length: 64 }).notNull(),
	userId: varchar("user_id", { length: 36 }).notNull(),
	goodsId: varchar("goods_id", { length: 36 }).notNull(),
	goodsName: varchar("goods_name", { length: 100 }).notNull(),
	goodsCover: varchar("goods_cover", { length: 500 }),
	goodsType: varchar("goods_type", { length: 20 }),
	unitPrice: decimal("unit_price", { precision: 12, scale: 2 }).notNull(),
	priceSource: varchar("price_source", { length: 20 }).default('base').notNull(),
	levelId: varchar("level_id", { length: 36 }),
	quantity: int().default(1).notNull(),
	totalAmount: decimal("total_amount", { precision: 12, scale: 2 }).notNull(),
	discountAmount: decimal("discount_amount", { precision: 12, scale: 2 }).default('0.00').notNull(),
	payAmount: decimal("pay_amount", { precision: 12, scale: 2 }).notNull(),
	giftAmount: decimal("gift_amount", { precision: 12, scale: 2 }).default('0.00').notNull(),
	rechargeAmount: decimal("recharge_amount", { precision: 12, scale: 2 }).default('0.00').notNull(),
	payMode: varchar("pay_mode", { length: 20 }).default('balance').notNull(),
	status: varchar({ length: 10 }).default('WP').notNull(),
	couponId: varchar("coupon_id", { length: 36 }),
	couponCode: varchar("coupon_code", { length: 32 }),
	freezeId: varchar("freeze_id", { length: 36 }),
	payOrderId: varchar("pay_order_id", { length: 36 }),
	payChannelCode: varchar("pay_channel_code", { length: 30 }),
	contact: varchar({ length: 50 }),
	fulfillStatus: varchar("fulfill_status", { length: 20 }).default('none').notNull(),
	fulfilledAt: timestamp("fulfilled_at", { mode: 'string' }),
	fulfillRemark: varchar("fulfill_remark", { length: 255 }),
	fulfillOperatorId: varchar("fulfill_operator_id", { length: 36 }),
	expireAt: timestamp("expire_at", { mode: 'string' }),
	paidAt: timestamp("paid_at", { mode: 'string' }),
	finishedAt: timestamp("finished_at", { mode: 'string' }),
	closedAt: timestamp("closed_at", { mode: 'string' }),
	closeReason: varchar("close_reason", { length: 255 }),
	failReason: varchar("fail_reason", { length: 500 }),
	remark: varchar({ length: 255 }),
	createdBy: varchar("created_by", { length: 36 }),
	createdAt: timestamp("created_at", { mode: 'string' }).defaultNow().notNull(),
	updatedBy: varchar("updated_by", { length: 36 }),
	updatedAt: timestamp("updated_at", { mode: 'string' }).defaultNow().onUpdateNow().notNull(),
	isDeleted: tinyint("is_deleted").default(0),
},
(table) => [
	index("idx_order_user").on(table.userId, table.createdAt),
	index("idx_order_status").on(table.status, table.expireAt),
	index("idx_order_fulfill").on(table.fulfillStatus, table.createdAt),
	index("idx_order_goods").on(table.goodsId),
	primaryKey({ columns: [table.id], name: "sys_order_id" }),
	unique("uk_order_no").on(table.orderNo),
	unique("uk_order_request").on(table.requestId),
]);
