import { mysqlTable, primaryKey, unique, index, varchar, tinyint, int, timestamp, json } from "drizzle-orm/mysql-core"

export const sysPayChannel = mysqlTable("sys_pay_channel", {
	id: varchar({ length: 36 }).notNull(),
	configKey: varchar("config_key", { length: 50 }).notNull(),
	configName: varchar("config_name", { length: 50 }).notNull(),
	channelCode: varchar("channel_code", { length: 30 }).notNull(),
	mode: varchar({ length: 10 }).default('live').notNull(),
	currency: varchar({ length: 10 }).default('CNY').notNull(),
	config: json(),
	notifyUrl: varchar("notify_url", { length: 500 }),
	returnUrl: varchar("return_url", { length: 500 }),
	cancelUrl: varchar("cancel_url", { length: 500 }),
	orderTimeoutMinutes: int("order_timeout_minutes").default(30).notNull(),
	isDefault: tinyint("is_default").default(0).notNull(),
	verifyStatus: tinyint("verify_status").default(0),
	verifyTime: timestamp("verify_time", { mode: 'string' }),
	verifyMessage: varchar("verify_message", { length: 500 }),
	status: tinyint().default(1).notNull(),
	sortOrder: int("sort_order").default(0),
	ipAllowlist: varchar("ip_allowlist", { length: 500 }),
	remark: varchar({ length: 255 }),
	createdBy: varchar("created_by", { length: 36 }),
	createdAt: timestamp("created_at", { mode: 'string' }).defaultNow().notNull(),
	updatedBy: varchar("updated_by", { length: 36 }),
	updatedAt: timestamp("updated_at", { mode: 'string' }).defaultNow().onUpdateNow().notNull(),
	isDeleted: tinyint("is_deleted").default(0),
},
(table) => [
	index("idx_pay_channel_code_status").on(table.channelCode, table.status),
	index("idx_pay_channel_default_sort").on(table.isDefault, table.sortOrder),
	primaryKey({ columns: [table.id], name: "sys_pay_channel_id" }),
	unique("uk_pay_channel_key").on(table.configKey),
]);
