import { mysqlTable, primaryKey, unique, index, varchar, tinyint, timestamp, decimal, json, text } from "drizzle-orm/mysql-core"

export const sysPayNotifyLog = mysqlTable("sys_pay_notify_log", {
	id: varchar({ length: 36 }).notNull(),
	channelId: varchar("channel_id", { length: 36 }),
	channelCode: varchar("channel_code", { length: 30 }).notNull(),
	orderId: varchar("order_id", { length: 36 }),
	outTradeNo: varchar("out_trade_no", { length: 64 }).notNull(),
	providerOrderId: varchar("provider_order_id", { length: 128 }),
	transactionId: varchar("transaction_id", { length: 128 }),
	amount: decimal({ precision: 10, scale: 2 }),
	currency: varchar({ length: 10 }),
	providerStatus: varchar("provider_status", { length: 32 }),
	status: varchar({ length: 10 }),
	source: varchar({ length: 20 }).default('notify').notNull(),
	dedupKey: varchar("dedup_key", { length: 128 }),
	signValid: tinyint("sign_valid").default(0).notNull(),
	processResult: varchar("process_result", { length: 20 }).notNull(),
	message: varchar({ length: 500 }),
	rawBody: text("raw_body"),
	rawHeaders: json("raw_headers"),
	clientIp: varchar("client_ip", { length: 64 }),
	userAgent: varchar("user_agent", { length: 255 }),
	createdBy: varchar("created_by", { length: 36 }),
	createdAt: timestamp("created_at", { mode: 'string' }).defaultNow().notNull(),
	updatedBy: varchar("updated_by", { length: 36 }),
	updatedAt: timestamp("updated_at", { mode: 'string' }).defaultNow().onUpdateNow().notNull(),
	isDeleted: tinyint("is_deleted").default(0),
},
(table) => [
	index("idx_pay_notify_channel_created").on(table.channelCode, table.createdAt),
	index("idx_pay_notify_order").on(table.orderId),
	index("idx_pay_notify_out_trade").on(table.outTradeNo, table.createdAt),
	index("idx_pay_notify_result").on(table.processResult),
	primaryKey({ columns: [table.id], name: "sys_pay_notify_log_id" }),
	unique("uk_pay_notify_dedup").on(table.dedupKey),
]);
