import { mysqlTable, primaryKey, unique, index, varchar, tinyint, int, timestamp, decimal, json, text } from "drizzle-orm/mysql-core"

export const sysPayOrder = mysqlTable("sys_pay_order", {
	id: varchar({ length: 36 }).notNull(),
	outTradeNo: varchar("out_trade_no", { length: 64 }).notNull(),
	channelId: varchar("channel_id", { length: 36 }),
	channelCode: varchar("channel_code", { length: 30 }).notNull(),
	providerOrderId: varchar("provider_order_id", { length: 128 }),
	transactionId: varchar("transaction_id", { length: 128 }),
	bizType: varchar("biz_type", { length: 50 }).default('test').notNull(),
	subject: varchar({ length: 200 }).notNull(),
	amount: decimal({ precision: 10, scale: 2 }).notNull(),
	currency: varchar({ length: 10 }).default('CNY').notNull(),
	status: varchar({ length: 10 }).default('WP').notNull(),
	providerStatus: varchar("provider_status", { length: 32 }),
	payMode: varchar("pay_mode", { length: 20 }).default('qrcode').notNull(),
	qrImageUrl: varchar("qr_image_url", { length: 500 }),
	qrContent: text("qr_content"),
	payUrl: varchar("pay_url", { length: 500 }),
	notifyUrl: varchar("notify_url", { length: 500 }),
	attach: varchar({ length: 255 }),
	clientIp: varchar("client_ip", { length: 64 }),
	userAgent: varchar("user_agent", { length: 255 }),
	expireAt: timestamp("expire_at", { mode: 'string' }),
	paidAt: timestamp("paid_at", { mode: 'string' }),
	cancelledAt: timestamp("cancelled_at", { mode: 'string' }),
	lastQueryAt: timestamp("last_query_at", { mode: 'string' }),
	notifyCount: int("notify_count").default(0).notNull(),
	lastNotifyAt: timestamp("last_notify_at", { mode: 'string' }),
	failReason: varchar("fail_reason", { length: 500 }),
	providerData: json("provider_data"),
	remark: varchar({ length: 255 }),
	createdBy: varchar("created_by", { length: 36 }),
	createdAt: timestamp("created_at", { mode: 'string' }).defaultNow().notNull(),
	updatedBy: varchar("updated_by", { length: 36 }),
	updatedAt: timestamp("updated_at", { mode: 'string' }).defaultNow().onUpdateNow().notNull(),
	isDeleted: tinyint("is_deleted").default(0),
},
(table) => [
	index("idx_pay_order_biz_type").on(table.bizType),
	index("idx_pay_order_channel_created").on(table.channelCode, table.createdAt),
	index("idx_pay_order_created_by").on(table.createdBy, table.createdAt),
	index("idx_pay_order_provider_order").on(table.providerOrderId),
	index("idx_pay_order_status_created").on(table.status, table.createdAt),
	primaryKey({ columns: [table.id], name: "sys_pay_order_id" }),
	unique("uk_pay_order_out_trade_no").on(table.outTradeNo),
]);
